#include "help.hpp"

#include <iostream>

namespace hbm_sim::cli {

void print_help(const char* argv0) {
  std::cout
      << "Usage: " << argv0 << " [options]\n\n"
      << "Options:\n"
      << "  --config PATH       v1 key=value or v2 sectioned config; CLI always overrides it\n"
      << "                      config timing keys may use nCK or JEDEC-style ns/us units\n"
      << "                      output parent directories are created automatically;\n"
      << "                      project examples use outputs/ (clean with: make clean-outputs)\n"
      << "  --standard hbm4|hbm3|lpddr6|lpddr5\n"
      << "  --preset NAME       select [preset.<standard>.<name>.*] from a v2 config\n"
      << "  --model-name NAME   label a standard-derived custom research model\n"
      << "  --validation-mode exploratory|standard|device\n"
      << "                      exploratory allows non-standard executable combinations;\n"
      << "                      standard/device add conformance and source requirements\n"
      << "                      device also requires named vendor profile + vendor timing\n"
      << "  --check-config      validate and resolve the model without running traffic\n"
      << "  --dump-resolved-config PATH  export the final executed model as INI\n"
      << "  --compare-preset    print active override differences\n"
      << "  --dump-config-diff PATH --explain-config KEY\n"
      << "  --list-presets --list-schedulers --list-row-policies\n"
      << "  --list-backends --list-phy-modes\n"
      << "                      unknown names fail; list commands show executable choices\n"
      << "  --stack-count N     independent memory stacks (default 1)\n"
      << "  --stack-mapping interleaved|blocked\n"
      << "  --stack-interleave-bytes N  stripe size; multiple of line_size\n"
      << "  --stack-ingress-buffer-size N --stack-dispatch-width N\n"
      << "  --stack-qos-policy fcfs|strict_priority\n"
      << "  --timing-profile NAME  expand standard timing profile before per-key overrides\n"
      << "  --vendor-profile NAME  source identity label; does not certify timing values\n"
      << "  config: timing_override_source=vendor|jedec|external_reference|research_default|derived\n"
      << "                      tags timing fields in the same section, independent of line order\n"
      << "  --speed-bin-mbps N --density-gb N --stack-height N\n"
      << "  --pattern stream|random\n"
      << "  --trace PATH        Trace lines: R|W ADDRESS [data=HEX] [expect=HEX] [mask=HEX]\n"
      << "                      maintenance: M REFpb|REFab|RFMpb|RFMab|REFdb ADDRESS\n"
      << "                      or BW|BR ADDRESS len=BYTES pattern/check=...; # comments allowed\n"
      << "  --memory-image PATH load initial sparse memory image (text or binary, auto-detected)\n"
      << "  --dump-memory-image PATH  dump final sparse memory image (.bin for binary, .txt for text)\n"
      << "  --dump-memory-csv PATH    dump final sparse memory image as Excel-friendly CSV\n"
      << "  --verify-golden PATH  post-simulation: verify memory_image bytes and init mask\n"
      << "                        against a golden file (text or binary, auto-detected)\n"
      << "  --mismatch-report PATH    write data mismatch report text after simulation\n"
      << "  --fail-on-data-mismatch   return 3 when an expected read mismatches (default)\n"
      << "  --allow-data-mismatch     report mismatches without failing the process\n"
      << "  --dump-thermal-map PATH   dump touched floorplan tiles with energy/temperature\n"
      << "  --floorplan true|false    enable bank-to-layer/tile physical placement model\n"
      << "  --power-model true|false  enable command energy accounting for storage events\n"
      << "  --thermal-model true|false  enable RC-style tile temperature update\n"
      << "  --power-source configured_pj|dramsim3_idd  command-energy source\n"
      << "  --power-scale FLOAT       multiply all configured command energy values\n"
      << "  --thermal-ambient-c FLOAT --thermal-cooling-per-cycle FLOAT\n"
      << "  --thermal-rise-c-per-pj FLOAT\n"
      << "  --memory-backend sparse|mmap_sparse|chunk_file\n"
      << "  --memory-capacity-bytes N --memory-data-file PATH\n"
      << "                      multi-stack paths accept {stack}; otherwise .stackN is inserted\n"
      << "  --memory-init-file PATH --memory-meta-file PATH --memory-presence-file PATH\n"
      << "  --memory-chunk-size BYTES --memory-chunk-cache-entries N\n"
      << "                      selectable payload backend for sparse/full-capacity workloads\n"
      << "  --sparse-density-warning-pct PERCENT\n"
      << "  --topology-stats-scan-limit N  0 means unlimited detailed topology scan\n"
      << "  --thermal-grid-cols-per-tile N --thermal-grid-rows-per-tile N\n"
      << "                      split each bank tile into DRAMsim3-style thermal grids\n"
      << "  --thermal-coupling true|false  enable sparse 3D RC neighbor coupling\n"
      << "  --thermal-lateral-coupling F --thermal-vertical-coupling F\n"
      << "  --thermal-tsv-coupling-scale F --thermal-tsvs-per-grid N\n"
      << "                      TSV-aware vertical thermal coupling knobs\n"
      << "  --subarrays-per-bank N --mats-per-subarray-x N --mats-per-subarray-y N\n"
      << "  --cells-per-mat-x N --cells-per-mat-y N --microbumps-x N --microbumps-y N\n"
      << "                      physical subarray/mat/cell/microbump coordinate model\n"
      << "  --ecc-shadow true|false --ecc-check-on-read true|false\n"
      << "  --ecc-correct-single-bit true|false --ecc-inject-period N\n"
      << "                      SECDED shadow model over real payload lines\n"
      << "  --power-vdd V --idd0 MA --idd2n MA --idd3n MA --idd4r MA --idd4w MA\n"
      << "  --idd5ab MA --idd5pb MA --idd6x MA --idd-devices-per-rank N\n"
      << "  --idd-burst-cycles N  override IDD burst duration in nCK (0 uses nBL)\n"
      << "                      IDD/VDD inputs for --power-source dramsim3_idd\n"
      << "  --requests N        In trace mode, caps expanded requests; 0 reads the whole trace\n"
      << "  --read-ratio PERCENT\n"
      << "  --seed N\n"
      << "  --random-address-space-bytes N  cap random system addresses; 0 uses model capacity\n"
      << "  --addr-stride BYTES\n"
      << "  --inject-interval N  frontend injection interval in controller ticks\n"
      << "  --init-sequence none|auto|hbm|hbm3|hbm4|lpddr|lpddr5|lpddr6|lpddr6_full\n"
      << "  --init-sequence-interval N  control sequence injection interval\n"
      << "  --read-buffer-size N\n"
      << "  --write-buffer-size N\n"
      << "  --priority-buffer-size N\n"
      << "  --max-cycles N\n"
      << "  --progress-interval N  write periodic progress to stderr; 0 disables it\n"
      << "  --stats-view summary|diagnostic  summary is the default English report; diagnostic is audit-only\n"
      << "  --stats-json <path>        schema 2 model/parameters/metrics/validation; diagnostic adds audit fields\n"
      << "  --single-controller  run one controller for isolated experiments\n"
      << "  --scheduler frfcfs|fcfs\n"
      << "  --row-policy open_page|closed_page|closed_cap\n"
      << "  --row-policy-cap N  ClosedCAP column accesses before closing\n"
      << "  --mem-phy direct|behavioral  select compatibility bypass or online Mem PHY\n"
      << "  --dfi-version VER  label the modeled DFI target (default: 6.0)\n"
      << "  --addr-mapping default|RoBaRaCoCh|ChRaBaRoCo|RoCoRaBaCh\n"
      << "  --dram-transaction-bytes N  payload bytes carried by one RD/WR command\n"
      << "  --channel-mapper decoded|round_robin|xor\n"
      << "  --lpddr-efficiency normal|static|dynamic\n"
      << "  --lpddr-dvfs nominal|low|disabled\n"
      << "  --lpddr-wck cas_sync|always_on  (burst_sync is reserved, not implemented)\n"
      << "  --dfi-phase-count N  DFI beat trace phase count; 0 derives from tick_multiplier\n"
      << "  --dfi-data-lane-bytes N  DFI bytes per beat; 0 derives from transaction_bytes/nBL\n"
      << "  --dfi-read-latency-nck N --dfi-write-latency-nck N\n"
      << "  --metadata-bits-per-request N\n"
      << "  --ecc-bits-per-request N\n"
      << "  --rfm-act-threshold N\n"
      << "  --rfm-decrement N\n"
      << "  --refresh-policy per_bank|all_bank\n"
      << "  --refresh-temperature normal|high|extended\n"
      << "  --rfm-policy per_bank|all_bank\n"
      << "  --refresh-postpone-limit N --refresh-pullin-limit N --refresh-credit-limit N\n"
      << "  --hbm-link-crc off|crc16\n"
      << "  --hbm-link-crc-bits N --hbm-ras-metadata-bits N --hbm-ecc-bits N\n"
      << "  --hbm-link-retry true|false\n"
      << "  --lpddr-link-protection true|false\n"
      << "  --lpddr-dbi true|false\n"
      << "  --lpddr-dbi-bits N --lpddr-link-ecc-bits N\n"
      << "  --lpddr-link-ecc true|false\n"
      << "  --lpddr-ca-parity true|false\n"
      << "  --lpddr-ca-parity-bits N\n"
      << "  --low-power off|power_down|self_refresh\n"
      << "  --low-power-entry-cycles N --low-power-exit-cycles N --self-refresh-exit-cycles N\n"
      << "  --strict-timing-table  fail if preset still has vendor-required defaults\n"
      << "  --cmd-trace PATH    write issued command trace as CSV\n"
      << "  --response-trace PATH  stream completed HostResponse records to CSV\n"
      << "                      (default MemorySystem path only; responses are consumed online)\n"
      << "  --transaction-response-trace PATH  stream completed DRAM transactions to CSV\n"
      << "  --response-delivery-mode disabled|host|transaction|both\n"
      << "                      select externally visible response view; trace paths infer it\n"
      << "  --host-response-queue-capacity N\n"
      << "  --transaction-response-queue-capacity N\n"
      << "                      finite response queues; 0 means unlimited, CLI consumer is ready\n"
      << "  --dfi-trace PATH    write DFI command/data beat trace as CSV\n"
      << "  --dfi-signal-trace PATH  write DFI-like signal trace CSV\n"
      << "  --dump-timing-table PATH  write timing table with source metadata as CSV\n"
      << "  --validate-cmd-trace  run command trace validation hook after simulation\n"
      << "  --validate-dfi-trace  validate DFI beat timing, signals, masks, and payloads\n"
      << "  --help\n";
}

}  // namespace hbm_sim::cli
