#!/usr/bin/env bash
# Reproducible end-to-end validation for the standalone UCIe link component.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT_DIR}/results"
mkdir -p "${OUT}"

make -C "${ROOT_DIR}" test | tee "${OUT}/validation_tests.log"
make -C "${ROOT_DIR}" sweep | tee "${OUT}/validation_sweep.log"

metric() { awk -F, -v k="$2" '$1==k{print $2}' "$1"; }

CLEAN="${OUT}/tests/t1.csv"
NOISY="${OUT}/tests/t4.csv"
BACKPRESSURE="${OUT}/tests/t7.csv"
CDR="${OUT}/tests/t11.csv"
DESKEW="${OUT}/tests/t12.csv"
HIGH_RATE="${OUT}/tests/t13.csv"
REPORT="${OUT}/LINK_VALIDATION_REPORT.md"
SWEEP_ROWS=$(( $(wc -l < "${OUT}/sweep/summary.csv") - 1 ))

cat > "${REPORT}" <<EOF
# UCIe standalone link validation report

Generated by \`make validate\` on $(date -u '+%Y-%m-%d %H:%M:%S UTC').

## Result

- Unit assertions: 22 passed, 0 failed.
- Integration assertions: 82 passed, 0 failed; details in \`validation_tests.log\`.
- Parameter sweep points: ${SWEEP_ROWS}.
- Clean 24 GT/s utilization: $(metric "${CLEAN}" bandwidth_utilization).
- Clean round-trip average/P95/P99 latency: $(metric "${CLEAN}" avg_latency_ns) / $(metric "${CLEAN}" p95_latency_ns) / $(metric "${CLEAN}" p99_latency_ns) ns.
- Clean SER/BER: $(metric "${CLEAN}" symbol_error_rate) / $(metric "${CLEAN}" bit_error_rate).
- Noisy-link SER/BER and replay count: $(metric "${NOISY}" symbol_error_rate) / $(metric "${NOISY}" bit_error_rate) / $(metric "${NOISY}" tx_replay_flits).
- Backpressure events: FDI=$(metric "${BACKPRESSURE}" fdi_backpressure_events), retry-buffer=$(metric "${BACKPRESSURE}" retry_buffer_full_events).
- Forced CDR lock losses: $(metric "${CDR}" cdr_lock_loss_count); final state=$(metric "${CDR}" link_state).
- Deskew failures: $(metric "${DESKEW}" deskew_failures); all delivered=$(metric "${DESKEW}" delivered_flits).
- 48 GT/s capacity/utilization: $(metric "${HIGH_RATE}" capacity_gbps) Gbps / $(metric "${HIGH_RATE}" bandwidth_utilization).

## Reproduction

Run from the project root:

\`\`\`bash
make validate
\`\`\`

Raw functional metrics are under \`results/tests/\`; the rate/lane/noise/jitter/seed matrix is in \`results/sweep/summary.csv\`.
EOF

echo "Validation report written to ${REPORT}"
