Import('*')
env.Append(CPPPATH=[Dir('#/src/systemc/ext')])
SimObject('Gem5Axi.py', sim_objects=['AxiDemo', 'AxiPacketTester'])
Source('axi_master.cc')
Source('axi_ram.cc')
Source('axi_demo.cc')
Source('packet_tester.cc')


# Compile protocol sources against gem5's own SystemC implementation.
import os
project_root = os.path.dirname(Dir('.').srcnode().abspath)
env.Append(CPPPATH=[os.path.join(project_root, 'gem5_new/libhettrace/include')])
aou_root = os.path.join(project_root, 'axi2flit/systemc')
ucie_root = os.path.join(project_root, 'ucie-model/src')
env.Append(CPPPATH=[os.path.join(project_root, 'protocol/include'), aou_root + '/include', aou_root + '/integration', ucie_root])
Source('aou_backend.cc')
Source('aou_axi2flit.cc')
Source('aou_flit_packer.cc')
Source('aou_flit_unpacker.cc')
Source('ramulator_backend.cc')
env.Append(CPPPATH=[project_root])
ramulator_build = os.path.join(project_root, 'build', 'ramulator2', 'lib')
env.Append(LIBPATH=[ramulator_build], LIBS=['storagestacked_ramulator2'], RPATH=[ramulator_build])
from SCons.Script import ARGUMENTS
if ARGUMENTS.get('SS_HAVE_MEMSIM', '0') == '1':
    env.Append(CPPDEFINES=['SS_HAVE_MEMSIM'])
    Source('memsim_backend.cc')
    memsim_root = os.path.join(project_root, 'mem_sim')
    env.Append(CPPPATH=[memsim_root + '/integration'])
    env.Append(LIBPATH=[memsim_root + '/build-unified'], LIBS=['storagestacked_memsim'])
    env.Append(RPATH=[memsim_root + '/build-unified'])
