###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/plugin/impl/drampower.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class DRAMPower(Component):
    impl = "DRAMPower"
    memspec_path = Param(str, required=True)
    strict_validation = Param(bool, default=True)
    include_interface = Param(bool, default=True)
    read_toggle_rate = Param(float, default=0.5, cpp_type="double")
    write_toggle_rate = Param(float, default=0.5, cpp_type="double")
    read_duty_cycle = Param(float, default=0.5, cpp_type="double")
    write_duty_cycle = Param(float, default=0.5, cpp_type="double")
